'use strict';

angular.module('BlurAdmin', [
  'ngAnimate',
  'ui.bootstrap',
  'ui.sortable',
  'ui.router',
  'ui.grid', 'ui.grid.selection', 'ui.grid.exporter', 'ui.grid.pagination',
  'ui.grid.edit', 'ui.grid.moveColumns', 'ui.grid.saveState', 'ui.grid.resizeColumns', 'ui.grid.cellNav', 'ui.grid.pinning',
  'ui.indeterminate',
  'ui.mask',
  'teljs',
  'ui.bootstrap.datetimepicker',
  'moment-picker',
  'ngTouch',
  'toastr',
  'smart-table',
  "xeditable",
  'ui.slimscroll',
  'ngJsTree',
  'angular-progress-button-styles',
  'LocalStorageModule',
  'ngMessages',
  'naif.base64',
  '720kb.datepicker',
  'ui.timepicker',
  'ngScrollbars',
  'jQueryScrollbar',
  // 'angular.chosen',
  'BlurAdmin.theme',
  'BlurAdmin.pages',
  'BlurAdmin.common'
]);